export type FoodSeed = {
  slug: string // kebab-case unique
  name: string // display name
  category: 'nigerian' | 'global' | 'supplement' | 'restaurant'
  tags: string[] // searchable: ['rice','carb','staple','nigerian']

  // Per 100 g cooked-as-consumed (for composed dishes) or per 100 g as-is (for ingredients)
  kcal_per_100g: number
  protein_per_100g: number
  carbs_per_100g: number
  fat_per_100g: number
  fiber_per_100g: number

  // Default serving for one-tap entry
  default_serving_g: number
  default_serving_label: string // e.g. "1 medium plate", "1 handful"

  // Per-100g values came from: USDA / FAO / estimate (note in comment on the line when estimate)
}

export const foodDatabase: ReadonlyArray<FoodSeed> = [
  // ============================================================
  // NIGERIAN STAPLES (~80)
  // ============================================================

  // --- Rice dishes ---
  {
    slug: 'jollof-rice',
    name: 'Jollof Rice',
    category: 'nigerian',
    tags: ['rice', 'carb', 'nigerian', 'lunch', 'dinner', 'staple'],
    kcal_per_100g: 165,
    protein_per_100g: 3.2,
    carbs_per_100g: 27.0,
    fat_per_100g: 4.8,
    fiber_per_100g: 1.1,
    default_serving_g: 300,
    default_serving_label: '1 medium plate',
  }, // estimate — composed dish, typical recipe
  {
    slug: 'fried-rice-nigerian',
    name: 'Nigerian Fried Rice',
    category: 'nigerian',
    tags: ['rice', 'carb', 'nigerian', 'lunch', 'dinner', 'staple'],
    kcal_per_100g: 178,
    protein_per_100g: 4.2,
    carbs_per_100g: 26.5,
    fat_per_100g: 6.0,
    fiber_per_100g: 1.5,
    default_serving_g: 300,
    default_serving_label: '1 medium plate',
  }, // estimate — composed dish, typical recipe
  {
    slug: 'coconut-rice',
    name: 'Coconut Rice',
    category: 'nigerian',
    tags: ['rice', 'carb', 'nigerian', 'lunch', 'dinner'],
    kcal_per_100g: 188,
    protein_per_100g: 3.0,
    carbs_per_100g: 26.8,
    fat_per_100g: 7.8,
    fiber_per_100g: 1.2,
    default_serving_g: 300,
    default_serving_label: '1 medium plate',
  }, // estimate — composed dish
  {
    slug: 'white-rice-stew',
    name: 'White Rice with Stew',
    category: 'nigerian',
    tags: ['rice', 'carb', 'nigerian', 'lunch', 'dinner', 'staple'],
    kcal_per_100g: 155,
    protein_per_100g: 3.5,
    carbs_per_100g: 25.0,
    fat_per_100g: 4.3,
    fiber_per_100g: 0.8,
    default_serving_g: 300,
    default_serving_label: '1 medium plate',
  }, // estimate — plated combo
  {
    slug: 'ofada-rice',
    name: 'Ofada Rice with Ayamase',
    category: 'nigerian',
    tags: ['rice', 'carb', 'nigerian', 'lunch', 'dinner'],
    kcal_per_100g: 170,
    protein_per_100g: 4.0,
    carbs_per_100g: 26.0,
    fat_per_100g: 5.5,
    fiber_per_100g: 2.0,
    default_serving_g: 300,
    default_serving_label: '1 medium plate',
  }, // estimate — composed dish
  {
    slug: 'tuwo-shinkafa',
    name: 'Tuwo Shinkafa',
    category: 'nigerian',
    tags: ['rice', 'swallow', 'carb', 'nigerian', 'northern'],
    kcal_per_100g: 130,
    protein_per_100g: 2.7,
    carbs_per_100g: 28.2,
    fat_per_100g: 0.3,
    fiber_per_100g: 0.4,
    default_serving_g: 250,
    default_serving_label: '1 serving',
  }, // FAO — rice dough
  {
    slug: 'jollof-rice-party',
    name: 'Party Jollof Rice (smoky)',
    category: 'nigerian',
    tags: ['rice', 'carb', 'nigerian', 'party', 'staple'],
    kcal_per_100g: 180,
    protein_per_100g: 3.4,
    carbs_per_100g: 26.5,
    fat_per_100g: 6.5,
    fiber_per_100g: 1.2,
    default_serving_g: 300,
    default_serving_label: '1 party plate',
  }, // estimate — oilier than home jollof

  // --- Swallows ---
  {
    slug: 'pounded-yam',
    name: 'Pounded Yam',
    category: 'nigerian',
    tags: ['swallow', 'carb', 'nigerian', 'staple', 'yam'],
    kcal_per_100g: 118,
    protein_per_100g: 1.5,
    carbs_per_100g: 27.9,
    fat_per_100g: 0.1,
    fiber_per_100g: 3.9,
    default_serving_g: 250,
    default_serving_label: '1 serving',
  }, // FAO
  {
    slug: 'eba-garri',
    name: 'Eba (Garri)',
    category: 'nigerian',
    tags: ['swallow', 'carb', 'nigerian', 'staple', 'cassava'],
    kcal_per_100g: 157,
    protein_per_100g: 1.4,
    carbs_per_100g: 37.0,
    fat_per_100g: 0.2,
    fiber_per_100g: 1.8,
    default_serving_g: 250,
    default_serving_label: '1 wrap',
  }, // FAO — cassava flour
  {
    slug: 'amala',
    name: 'Amala (Yam Flour Swallow)',
    category: 'nigerian',
    tags: ['swallow', 'carb', 'nigerian', 'staple', 'yam'],
    kcal_per_100g: 112,
    protein_per_100g: 1.2,
    carbs_per_100g: 26.3,
    fat_per_100g: 0.2,
    fiber_per_100g: 2.3,
    default_serving_g: 200,
    default_serving_label: '1 serving',
  }, // FAO — elubo
  {
    slug: 'fufu',
    name: 'Fufu (Cassava)',
    category: 'nigerian',
    tags: ['swallow', 'carb', 'nigerian', 'staple', 'cassava'],
    kcal_per_100g: 120,
    protein_per_100g: 0.7,
    carbs_per_100g: 29.0,
    fat_per_100g: 0.2,
    fiber_per_100g: 1.6,
    default_serving_g: 250,
    default_serving_label: '1 wrap',
  }, // FAO
  {
    slug: 'semo',
    name: 'Semo (Semovita)',
    category: 'nigerian',
    tags: ['swallow', 'carb', 'nigerian', 'staple', 'wheat'],
    kcal_per_100g: 155,
    protein_per_100g: 5.0,
    carbs_per_100g: 32.0,
    fat_per_100g: 0.5,
    fiber_per_100g: 1.0,
    default_serving_g: 250,
    default_serving_label: '1 wrap',
  }, // estimate — wheat semolina cooked
  {
    slug: 'wheat-swallow',
    name: 'Wheat Swallow',
    category: 'nigerian',
    tags: ['swallow', 'carb', 'nigerian', 'wheat'],
    kcal_per_100g: 148,
    protein_per_100g: 5.5,
    carbs_per_100g: 30.5,
    fat_per_100g: 0.6,
    fiber_per_100g: 3.8,
    default_serving_g: 250,
    default_serving_label: '1 wrap',
  }, // estimate — whole wheat flour swallow
  {
    slug: 'starch',
    name: 'Starch (Cassava starch, Warri-style)',
    category: 'nigerian',
    tags: ['swallow', 'carb', 'nigerian', 'cassava'],
    kcal_per_100g: 158,
    protein_per_100g: 0.3,
    carbs_per_100g: 38.8,
    fat_per_100g: 0.2,
    fiber_per_100g: 0.8,
    default_serving_g: 250,
    default_serving_label: '1 wrap',
  }, // FAO
  {
    slug: 'pounded-plantain',
    name: 'Plantain Fufu',
    category: 'nigerian',
    tags: ['swallow', 'carb', 'nigerian', 'plantain'],
    kcal_per_100g: 122,
    protein_per_100g: 1.3,
    carbs_per_100g: 29.0,
    fat_per_100g: 0.3,
    fiber_per_100g: 2.2,
    default_serving_g: 250,
    default_serving_label: '1 wrap',
  }, // estimate — cooked plantain dough

  // --- Soups ---
  {
    slug: 'egusi-soup',
    name: 'Egusi Soup',
    category: 'nigerian',
    tags: ['soup', 'nigerian', 'staple', 'fat', 'protein'],
    kcal_per_100g: 175,
    protein_per_100g: 7.5,
    carbs_per_100g: 5.0,
    fat_per_100g: 14.2,
    fiber_per_100g: 2.2,
    default_serving_g: 200,
    default_serving_label: '1 bowl',
  }, // estimate — melon seed soup
  {
    slug: 'okra-soup',
    name: 'Okra Soup',
    category: 'nigerian',
    tags: ['soup', 'nigerian', 'vegetable', 'staple'],
    kcal_per_100g: 95,
    protein_per_100g: 5.0,
    carbs_per_100g: 4.0,
    fat_per_100g: 6.5,
    fiber_per_100g: 2.5,
    default_serving_g: 200,
    default_serving_label: '1 bowl',
  }, // estimate — with palm oil and fish
  {
    slug: 'efo-riro',
    name: 'Efo Riro',
    category: 'nigerian',
    tags: ['soup', 'nigerian', 'vegetable', 'spinach'],
    kcal_per_100g: 110,
    protein_per_100g: 6.8,
    carbs_per_100g: 3.5,
    fat_per_100g: 7.8,
    fiber_per_100g: 2.8,
    default_serving_g: 200,
    default_serving_label: '1 bowl',
  }, // estimate — vegetable stew
  {
    slug: 'ogbono-soup',
    name: 'Ogbono Soup',
    category: 'nigerian',
    tags: ['soup', 'nigerian', 'staple', 'fat'],
    kcal_per_100g: 165,
    protein_per_100g: 6.8,
    carbs_per_100g: 4.5,
    fat_per_100g: 13.5,
    fiber_per_100g: 2.0,
    default_serving_g: 200,
    default_serving_label: '1 bowl',
  }, // estimate — wild mango seed soup
  {
    slug: 'afang-soup',
    name: 'Afang Soup',
    category: 'nigerian',
    tags: ['soup', 'nigerian', 'vegetable', 'efik'],
    kcal_per_100g: 130,
    protein_per_100g: 7.5,
    carbs_per_100g: 4.0,
    fat_per_100g: 9.0,
    fiber_per_100g: 3.0,
    default_serving_g: 200,
    default_serving_label: '1 bowl',
  }, // estimate — Efik soup
  {
    slug: 'edikang-ikong',
    name: 'Edikang Ikong Soup',
    category: 'nigerian',
    tags: ['soup', 'nigerian', 'vegetable', 'efik'],
    kcal_per_100g: 135,
    protein_per_100g: 8.0,
    carbs_per_100g: 4.5,
    fat_per_100g: 9.0,
    fiber_per_100g: 3.2,
    default_serving_g: 200,
    default_serving_label: '1 bowl',
  }, // estimate — vegetable-heavy Efik soup
  {
    slug: 'pepper-soup-goat',
    name: 'Goat Pepper Soup',
    category: 'nigerian',
    tags: ['soup', 'nigerian', 'protein', 'meat', 'goat'],
    kcal_per_100g: 120,
    protein_per_100g: 14.0,
    carbs_per_100g: 1.0,
    fat_per_100g: 6.7,
    fiber_per_100g: 0.3,
    default_serving_g: 250,
    default_serving_label: '1 bowl',
  }, // estimate — light broth with goat
  {
    slug: 'pepper-soup-fish',
    name: 'Catfish Pepper Soup',
    category: 'nigerian',
    tags: ['soup', 'nigerian', 'protein', 'fish'],
    kcal_per_100g: 95,
    protein_per_100g: 13.5,
    carbs_per_100g: 0.8,
    fat_per_100g: 4.2,
    fiber_per_100g: 0.2,
    default_serving_g: 250,
    default_serving_label: '1 bowl',
  }, // estimate — catfish broth
  {
    slug: 'banga-soup',
    name: 'Banga Soup',
    category: 'nigerian',
    tags: ['soup', 'nigerian', 'fat', 'palm'],
    kcal_per_100g: 190,
    protein_per_100g: 6.5,
    carbs_per_100g: 4.0,
    fat_per_100g: 17.0,
    fiber_per_100g: 1.5,
    default_serving_g: 200,
    default_serving_label: '1 bowl',
  }, // estimate — palm fruit soup
  {
    slug: 'oha-soup',
    name: 'Oha Soup',
    category: 'nigerian',
    tags: ['soup', 'nigerian', 'igbo', 'vegetable'],
    kcal_per_100g: 150,
    protein_per_100g: 7.0,
    carbs_per_100g: 5.0,
    fat_per_100g: 11.0,
    fiber_per_100g: 2.2,
    default_serving_g: 200,
    default_serving_label: '1 bowl',
  }, // estimate — Igbo soup
  {
    slug: 'bitterleaf-soup',
    name: 'Bitterleaf Soup (Ofe Onugbu)',
    category: 'nigerian',
    tags: ['soup', 'nigerian', 'igbo', 'vegetable'],
    kcal_per_100g: 145,
    protein_per_100g: 7.2,
    carbs_per_100g: 4.5,
    fat_per_100g: 10.5,
    fiber_per_100g: 2.0,
    default_serving_g: 200,
    default_serving_label: '1 bowl',
  }, // estimate — cocoyam-thickened
  {
    slug: 'gbegiri-soup',
    name: 'Gbegiri (Bean Soup)',
    category: 'nigerian',
    tags: ['soup', 'nigerian', 'protein', 'bean'],
    kcal_per_100g: 110,
    protein_per_100g: 6.5,
    carbs_per_100g: 14.0,
    fat_per_100g: 2.8,
    fiber_per_100g: 3.5,
    default_serving_g: 200,
    default_serving_label: '1 bowl',
  }, // estimate — blended beans

  // --- Proteins ---
  {
    slug: 'grilled-chicken-nigerian',
    name: 'Grilled Chicken (Nigerian style)',
    category: 'nigerian',
    tags: ['protein', 'nigerian', 'meat', 'poultry', 'lean'],
    kcal_per_100g: 190,
    protein_per_100g: 26.0,
    carbs_per_100g: 1.0,
    fat_per_100g: 9.0,
    fiber_per_100g: 0,
    default_serving_g: 120,
    default_serving_label: '1 quarter',
  }, // estimate — peppered grilled chicken
  {
    slug: 'suya',
    name: 'Suya (Beef Skewer)',
    category: 'nigerian',
    tags: ['protein', 'nigerian', 'meat', 'beef', 'street'],
    kcal_per_100g: 235,
    protein_per_100g: 27.0,
    carbs_per_100g: 3.0,
    fat_per_100g: 12.8,
    fiber_per_100g: 1.0,
    default_serving_g: 80,
    default_serving_label: '1 average suya stick',
  }, // estimate — spiced beef skewer
  {
    slug: 'suya-chicken',
    name: 'Chicken Suya',
    category: 'nigerian',
    tags: ['protein', 'nigerian', 'meat', 'poultry', 'street'],
    kcal_per_100g: 200,
    protein_per_100g: 27.0,
    carbs_per_100g: 2.5,
    fat_per_100g: 9.0,
    fiber_per_100g: 0.8,
    default_serving_g: 80,
    default_serving_label: '1 stick',
  }, // estimate
  {
    slug: 'fried-fish-nigerian',
    name: 'Fried Fish (Nigerian)',
    category: 'nigerian',
    tags: ['protein', 'nigerian', 'fish', 'fried'],
    kcal_per_100g: 220,
    protein_per_100g: 22.0,
    carbs_per_100g: 2.0,
    fat_per_100g: 13.5,
    fiber_per_100g: 0,
    default_serving_g: 120,
    default_serving_label: '1 piece',
  }, // estimate
  {
    slug: 'peppered-fish',
    name: 'Peppered Fish',
    category: 'nigerian',
    tags: ['protein', 'nigerian', 'fish'],
    kcal_per_100g: 180,
    protein_per_100g: 22.5,
    carbs_per_100g: 3.0,
    fat_per_100g: 8.5,
    fiber_per_100g: 0.8,
    default_serving_g: 150,
    default_serving_label: '1 plate',
  }, // estimate
  {
    slug: 'roasted-fish',
    name: 'Roasted Fish (Tilapia)',
    category: 'nigerian',
    tags: ['protein', 'nigerian', 'fish', 'lean'],
    kcal_per_100g: 150,
    protein_per_100g: 24.0,
    carbs_per_100g: 1.0,
    fat_per_100g: 5.5,
    fiber_per_100g: 0,
    default_serving_g: 250,
    default_serving_label: '1 whole small fish',
  }, // estimate
  {
    slug: 'boiled-beef',
    name: 'Boiled Beef (Assorted)',
    category: 'nigerian',
    tags: ['protein', 'nigerian', 'meat', 'beef'],
    kcal_per_100g: 195,
    protein_per_100g: 26.0,
    carbs_per_100g: 0,
    fat_per_100g: 10.0,
    fiber_per_100g: 0,
    default_serving_g: 80,
    default_serving_label: '2 chunks',
  }, // estimate
  {
    slug: 'peppered-beef',
    name: 'Peppered Beef',
    category: 'nigerian',
    tags: ['protein', 'nigerian', 'meat', 'beef'],
    kcal_per_100g: 225,
    protein_per_100g: 24.0,
    carbs_per_100g: 3.5,
    fat_per_100g: 12.5,
    fiber_per_100g: 0.8,
    default_serving_g: 120,
    default_serving_label: '1 plate',
  }, // estimate
  {
    slug: 'fried-beef',
    name: 'Fried Beef',
    category: 'nigerian',
    tags: ['protein', 'nigerian', 'meat', 'beef'],
    kcal_per_100g: 270,
    protein_per_100g: 26.0,
    carbs_per_100g: 0.5,
    fat_per_100g: 18.0,
    fiber_per_100g: 0,
    default_serving_g: 80,
    default_serving_label: '2 chunks',
  }, // estimate
  {
    slug: 'goat-meat-boiled',
    name: 'Boiled Goat Meat',
    category: 'nigerian',
    tags: ['protein', 'nigerian', 'meat', 'goat'],
    kcal_per_100g: 175,
    protein_per_100g: 27.0,
    carbs_per_100g: 0,
    fat_per_100g: 7.5,
    fiber_per_100g: 0,
    default_serving_g: 80,
    default_serving_label: '2 chunks',
  }, // USDA — goat meat cooked
  {
    slug: 'isi-ewu',
    name: 'Isi Ewu (Goat Head)',
    category: 'nigerian',
    tags: ['protein', 'nigerian', 'meat', 'goat', 'igbo'],
    kcal_per_100g: 260,
    protein_per_100g: 20.0,
    carbs_per_100g: 3.0,
    fat_per_100g: 18.8,
    fiber_per_100g: 0.5,
    default_serving_g: 200,
    default_serving_label: '1 plate',
  }, // estimate — rich with palm oil and utazi
  {
    slug: 'nkwobi',
    name: 'Nkwobi (Cow Foot)',
    category: 'nigerian',
    tags: ['protein', 'nigerian', 'meat', 'igbo'],
    kcal_per_100g: 250,
    protein_per_100g: 21.0,
    carbs_per_100g: 2.0,
    fat_per_100g: 17.5,
    fiber_per_100g: 0.5,
    default_serving_g: 200,
    default_serving_label: '1 plate',
  }, // estimate — spiced cow foot
  {
    slug: 'turkey-boiled',
    name: 'Boiled Turkey (Nigerian)',
    category: 'nigerian',
    tags: ['protein', 'nigerian', 'meat', 'poultry'],
    kcal_per_100g: 170,
    protein_per_100g: 25.0,
    carbs_per_100g: 0,
    fat_per_100g: 7.5,
    fiber_per_100g: 0,
    default_serving_g: 100,
    default_serving_label: '1 piece',
  }, // estimate — boiled hard turkey
  {
    slug: 'turkey-fried',
    name: 'Fried Turkey (Nigerian)',
    category: 'nigerian',
    tags: ['protein', 'nigerian', 'meat', 'poultry'],
    kcal_per_100g: 240,
    protein_per_100g: 25.0,
    carbs_per_100g: 0.5,
    fat_per_100g: 15.0,
    fiber_per_100g: 0,
    default_serving_g: 100,
    default_serving_label: '1 piece',
  }, // estimate
  {
    slug: 'moi-moi',
    name: 'Moi Moi (Steamed Bean Pudding)',
    category: 'nigerian',
    tags: ['protein', 'nigerian', 'bean', 'staple'],
    kcal_per_100g: 155,
    protein_per_100g: 9.0,
    carbs_per_100g: 14.5,
    fat_per_100g: 6.8,
    fiber_per_100g: 4.0,
    default_serving_g: 120,
    default_serving_label: '1 wrap',
  }, // estimate — cowpea pudding
  {
    slug: 'akara',
    name: 'Akara (Bean Cake)',
    category: 'nigerian',
    tags: ['protein', 'nigerian', 'bean', 'breakfast', 'street'],
    kcal_per_100g: 220,
    protein_per_100g: 9.5,
    carbs_per_100g: 15.0,
    fat_per_100g: 13.5,
    fiber_per_100g: 3.5,
    default_serving_g: 60,
    default_serving_label: '2 pieces',
  }, // estimate — fried bean fritter
  {
    slug: 'ewa-agoyin',
    name: 'Ewa Agoyin',
    category: 'nigerian',
    tags: ['protein', 'nigerian', 'bean', 'staple'],
    kcal_per_100g: 150,
    protein_per_100g: 7.5,
    carbs_per_100g: 17.0,
    fat_per_100g: 5.8,
    fiber_per_100g: 5.0,
    default_serving_g: 250,
    default_serving_label: '1 serving',
  }, // estimate — mashed beans with pepper sauce
  {
    slug: 'beans-porridge',
    name: 'Beans Porridge (Adalu)',
    category: 'nigerian',
    tags: ['protein', 'nigerian', 'bean', 'staple'],
    kcal_per_100g: 130,
    protein_per_100g: 6.5,
    carbs_per_100g: 18.0,
    fat_per_100g: 3.5,
    fiber_per_100g: 4.5,
    default_serving_g: 300,
    default_serving_label: '1 bowl',
  }, // estimate

  // --- Snacks ---
  {
    slug: 'puff-puff',
    name: 'Puff Puff',
    category: 'nigerian',
    tags: ['snack', 'nigerian', 'carb', 'fried', 'street'],
    kcal_per_100g: 330,
    protein_per_100g: 6.0,
    carbs_per_100g: 43.0,
    fat_per_100g: 15.0,
    fiber_per_100g: 1.2,
    default_serving_g: 60,
    default_serving_label: '3 small balls',
  }, // estimate — fried sweet dough
  {
    slug: 'chin-chin',
    name: 'Chin-Chin',
    category: 'nigerian',
    tags: ['snack', 'nigerian', 'carb', 'fried'],
    kcal_per_100g: 455,
    protein_per_100g: 7.5,
    carbs_per_100g: 55.0,
    fat_per_100g: 22.5,
    fiber_per_100g: 2.0,
    default_serving_g: 50,
    default_serving_label: '1 small handful',
  }, // estimate
  {
    slug: 'plantain-chips-ipekere',
    name: 'Plantain Chips (Ipekere)',
    category: 'nigerian',
    tags: ['snack', 'nigerian', 'plantain', 'carb'],
    kcal_per_100g: 520,
    protein_per_100g: 2.3,
    carbs_per_100g: 59.0,
    fat_per_100g: 30.0,
    fiber_per_100g: 4.0,
    default_serving_g: 40,
    default_serving_label: '1 small pack',
  }, // estimate — fried plantain crisps
  {
    slug: 'boiled-corn',
    name: 'Boiled Corn',
    category: 'nigerian',
    tags: ['snack', 'nigerian', 'carb', 'corn'],
    kcal_per_100g: 96,
    protein_per_100g: 3.4,
    carbs_per_100g: 17.2,
    fat_per_100g: 1.5,
    fiber_per_100g: 2.4,
    default_serving_g: 150,
    default_serving_label: '1 medium cob',
  }, // USDA
  {
    slug: 'roasted-corn',
    name: 'Roasted Corn',
    category: 'nigerian',
    tags: ['snack', 'nigerian', 'carb', 'corn'],
    kcal_per_100g: 110,
    protein_per_100g: 4,
    carbs_per_100g: 20.5,
    fat_per_100g: 1.3,
    fiber_per_100g: 2.7,
    default_serving_g: 150,
    default_serving_label: '1 medium cob',
  }, // estimate — slight moisture loss vs boiled
  {
    slug: 'ube-pear',
    name: 'Ube (African Pear)',
    category: 'nigerian',
    tags: ['snack', 'nigerian', 'fat', 'fruit'],
    kcal_per_100g: 258,
    protein_per_100g: 2.5,
    carbs_per_100g: 3,
    fat_per_100g: 26.5,
    fiber_per_100g: 5.5,
    default_serving_g: 50,
    default_serving_label: '1 medium pear',
  }, // FAO — Dacryodes edulis
  {
    slug: 'agbalumo',
    name: 'Agbalumo (African Star Apple)',
    category: 'nigerian',
    tags: ['snack', 'nigerian', 'fruit'],
    kcal_per_100g: 65,
    protein_per_100g: 0.7,
    carbs_per_100g: 15.0,
    fat_per_100g: 0.2,
    fiber_per_100g: 2.5,
    default_serving_g: 60,
    default_serving_label: '1 medium fruit',
  }, // FAO — Chrysophyllum albidum
  {
    slug: 'groundnut-roasted',
    name: 'Roasted Groundnut (Peanut)',
    category: 'nigerian',
    tags: ['snack', 'nigerian', 'fat', 'protein', 'nuts'],
    kcal_per_100g: 585,
    protein_per_100g: 24,
    carbs_per_100g: 10.4,
    fat_per_100g: 49.7,
    fiber_per_100g: 8.0,
    default_serving_g: 30,
    default_serving_label: '1 small handful',
  }, // USDA
  {
    slug: 'kuli-kuli',
    name: 'Kuli Kuli (Groundnut Cake)',
    category: 'nigerian',
    tags: ['snack', 'nigerian', 'protein', 'fat', 'nuts'],
    kcal_per_100g: 560,
    protein_per_100g: 27.0,
    carbs_per_100g: 20.0,
    fat_per_100g: 41.0,
    fiber_per_100g: 7.0,
    default_serving_g: 40,
    default_serving_label: '1 stick',
  }, // estimate — fried peanut snack
  {
    slug: 'tiger-nut',
    name: 'Tiger Nut (Ofio)',
    category: 'nigerian',
    tags: ['snack', 'nigerian', 'fat', 'fiber'],
    kcal_per_100g: 400,
    protein_per_100g: 4.6,
    carbs_per_100g: 42,
    fat_per_100g: 24,
    fiber_per_100g: 13.0,
    default_serving_g: 30,
    default_serving_label: '1 small handful',
  }, // estimate — raw tiger nuts
  {
    slug: 'coconut-fresh',
    name: 'Fresh Coconut',
    category: 'nigerian',
    tags: ['snack', 'nigerian', 'fat', 'fruit'],
    kcal_per_100g: 354,
    protein_per_100g: 3.3,
    carbs_per_100g: 9.8,
    fat_per_100g: 33.5,
    fiber_per_100g: 9.0,
    default_serving_g: 40,
    default_serving_label: '1 small piece',
  }, // USDA
  {
    slug: 'coconut-candy',
    name: 'Coconut Candy',
    category: 'nigerian',
    tags: ['snack', 'nigerian', 'sweet'],
    kcal_per_100g: 440,
    protein_per_100g: 3.0,
    carbs_per_100g: 52.0,
    fat_per_100g: 25.0,
    fiber_per_100g: 4.5,
    default_serving_g: 30,
    default_serving_label: '1 small piece',
  }, // estimate

  // --- Beverages ---
  {
    slug: 'zobo',
    name: 'Zobo Drink',
    category: 'nigerian',
    tags: ['beverage', 'nigerian', 'hibiscus'],
    kcal_per_100g: 30,
    protein_per_100g: 0.2,
    carbs_per_100g: 7.3,
    fat_per_100g: 0.1,
    fiber_per_100g: 0.2,
    default_serving_g: 300,
    default_serving_label: '1 cup',
  }, // estimate — sweetened hibiscus
  {
    slug: 'kunnu-aya',
    name: 'Kunnu Aya (Tiger Nut Milk)',
    category: 'nigerian',
    tags: ['beverage', 'nigerian', 'tiger-nut'],
    kcal_per_100g: 75,
    protein_per_100g: 1.5,
    carbs_per_100g: 9.0,
    fat_per_100g: 3.6,
    fiber_per_100g: 0.8,
    default_serving_g: 300,
    default_serving_label: '1 cup',
  }, // estimate
  {
    slug: 'kunnu-zaki',
    name: 'Kunnu Zaki (Millet Drink)',
    category: 'nigerian',
    tags: ['beverage', 'nigerian', 'grain'],
    kcal_per_100g: 55,
    protein_per_100g: 1.2,
    carbs_per_100g: 11.5,
    fat_per_100g: 0.4,
    fiber_per_100g: 0.5,
    default_serving_g: 300,
    default_serving_label: '1 cup',
  }, // estimate
  {
    slug: 'chapman',
    name: 'Chapman (Home-Prepared)',
    category: 'nigerian',
    tags: ['beverage', 'nigerian', 'sweet'],
    kcal_per_100g: 60,
    protein_per_100g: 0.1,
    carbs_per_100g: 15.0,
    fat_per_100g: 0,
    fiber_per_100g: 0.1,
    default_serving_g: 300,
    default_serving_label: '1 glass',
  }, // estimate — mixed soda/fruit drink
  {
    slug: 'pap-ogi',
    name: 'Pap (Ogi)',
    category: 'nigerian',
    tags: ['beverage', 'nigerian', 'breakfast', 'grain'],
    kcal_per_100g: 55,
    protein_per_100g: 0.8,
    carbs_per_100g: 12.5,
    fat_per_100g: 0.2,
    fiber_per_100g: 0.5,
    default_serving_g: 300,
    default_serving_label: '1 bowl',
  }, // estimate — fermented corn

  // --- Street food / combos ---
  {
    slug: 'boli-plantain',
    name: 'Boli (Roasted Plantain)',
    category: 'nigerian',
    tags: ['street', 'nigerian', 'plantain', 'carb'],
    kcal_per_100g: 125,
    protein_per_100g: 1.3,
    carbs_per_100g: 30,
    fat_per_100g: 0.4,
    fiber_per_100g: 2.3,
    default_serving_g: 180,
    default_serving_label: '1 whole plantain',
  }, // USDA — ripe plantain roasted
  {
    slug: 'boli-groundnut',
    name: 'Boli + Groundnut',
    category: 'nigerian',
    tags: ['street', 'nigerian', 'combo'],
    kcal_per_100g: 220,
    protein_per_100g: 5.0,
    carbs_per_100g: 30.0,
    fat_per_100g: 9.0,
    fiber_per_100g: 3.5,
    default_serving_g: 200,
    default_serving_label: '1 serving',
  }, // estimate — plantain plus a handful of peanuts
  {
    slug: 'indomie-egg',
    name: 'Indomie-style Noodles + Egg',
    category: 'nigerian',
    tags: ['street', 'nigerian', 'noodles', 'combo'],
    kcal_per_100g: 180,
    protein_per_100g: 5.5,
    carbs_per_100g: 22.0,
    fat_per_100g: 7.8,
    fiber_per_100g: 1.2,
    default_serving_g: 250,
    default_serving_label: '1 plate (2 packs + 1 egg)',
  }, // estimate — instant noodles with egg
  {
    slug: 'bread-akara-pap',
    name: 'Bread + Akara + Pap Combo',
    category: 'nigerian',
    tags: ['street', 'nigerian', 'breakfast', 'combo'],
    kcal_per_100g: 210,
    protein_per_100g: 6.8,
    carbs_per_100g: 26.0,
    fat_per_100g: 8.5,
    fiber_per_100g: 2.0,
    default_serving_g: 350,
    default_serving_label: '1 breakfast combo',
  }, // estimate — combined per 100 g
  {
    slug: 'shawarma-nigerian',
    name: 'Shawarma (Nigerian Style)',
    category: 'nigerian',
    tags: ['street', 'nigerian', 'wrap', 'combo'],
    kcal_per_100g: 240,
    protein_per_100g: 11.0,
    carbs_per_100g: 22.0,
    fat_per_100g: 12.0,
    fiber_per_100g: 1.5,
    default_serving_g: 250,
    default_serving_label: '1 regular shawarma',
  }, // estimate — chicken/sausage with mayo
  {
    slug: 'meat-pie',
    name: 'Meat Pie (Nigerian)',
    category: 'nigerian',
    tags: ['street', 'nigerian', 'snack', 'pastry'],
    kcal_per_100g: 300,
    protein_per_100g: 7.5,
    carbs_per_100g: 30.0,
    fat_per_100g: 16.5,
    fiber_per_100g: 1.5,
    default_serving_g: 150,
    default_serving_label: '1 large meat pie',
  }, // estimate
  {
    slug: 'sausage-roll',
    name: 'Sausage Roll',
    category: 'nigerian',
    tags: ['street', 'nigerian', 'snack', 'pastry'],
    kcal_per_100g: 340,
    protein_per_100g: 8,
    carbs_per_100g: 28,
    fat_per_100g: 21.8,
    fiber_per_100g: 1.0,
    default_serving_g: 80,
    default_serving_label: '1 roll',
  }, // estimate
  {
    slug: 'scotch-egg',
    name: 'Scotch Egg (Nigerian)',
    category: 'nigerian',
    tags: ['street', 'nigerian', 'snack', 'protein'],
    kcal_per_100g: 270,
    protein_per_100g: 12.5,
    carbs_per_100g: 14.0,
    fat_per_100g: 18.0,
    fiber_per_100g: 0.8,
    default_serving_g: 100,
    default_serving_label: '1 scotch egg',
  }, // estimate
  {
    slug: 'doughnut-nigerian',
    name: 'Nigerian Doughnut',
    category: 'nigerian',
    tags: ['street', 'nigerian', 'snack', 'sweet'],
    kcal_per_100g: 385,
    protein_per_100g: 6.5,
    carbs_per_100g: 44.0,
    fat_per_100g: 20.0,
    fiber_per_100g: 1.5,
    default_serving_g: 60,
    default_serving_label: '1 doughnut',
  }, // estimate
  {
    slug: 'fish-roll',
    name: 'Fish Roll',
    category: 'nigerian',
    tags: ['street', 'nigerian', 'snack', 'pastry', 'fish'],
    kcal_per_100g: 310,
    protein_per_100g: 9,
    carbs_per_100g: 30,
    fat_per_100g: 17.1,
    fiber_per_100g: 1.2,
    default_serving_g: 90,
    default_serving_label: '1 roll',
  }, // estimate
  {
    slug: 'fried-yam',
    name: 'Fried Yam (Dundu)',
    category: 'nigerian',
    tags: ['street', 'nigerian', 'yam', 'carb'],
    kcal_per_100g: 220,
    protein_per_100g: 2.0,
    carbs_per_100g: 30.5,
    fat_per_100g: 10.0,
    fiber_per_100g: 3.5,
    default_serving_g: 150,
    default_serving_label: '1 serving',
  }, // estimate
  {
    slug: 'yam-egg-sauce',
    name: 'Boiled Yam + Egg Sauce',
    category: 'nigerian',
    tags: ['nigerian', 'yam', 'combo', 'breakfast'],
    kcal_per_100g: 150,
    protein_per_100g: 4.5,
    carbs_per_100g: 22.0,
    fat_per_100g: 5.0,
    fiber_per_100g: 2.0,
    default_serving_g: 350,
    default_serving_label: '1 plate',
  }, // estimate
  {
    slug: 'yam-porridge',
    name: 'Yam Porridge (Asaro)',
    category: 'nigerian',
    tags: ['nigerian', 'yam', 'staple'],
    kcal_per_100g: 128,
    protein_per_100g: 2.0,
    carbs_per_100g: 23.0,
    fat_per_100g: 3.5,
    fiber_per_100g: 2.5,
    default_serving_g: 300,
    default_serving_label: '1 bowl',
  }, // estimate
  {
    slug: 'dodo-fried-plantain',
    name: 'Dodo (Fried Plantain)',
    category: 'nigerian',
    tags: ['nigerian', 'plantain', 'carb', 'side'],
    kcal_per_100g: 190,
    protein_per_100g: 1.5,
    carbs_per_100g: 31.0,
    fat_per_100g: 7.0,
    fiber_per_100g: 2.2,
    default_serving_g: 100,
    default_serving_label: '1 side portion',
  }, // estimate
  {
    slug: 'bole-plantain-grilled',
    name: 'Bole (Grilled Plantain)',
    category: 'nigerian',
    tags: ['street', 'nigerian', 'plantain', 'carb'],
    kcal_per_100g: 120,
    protein_per_100g: 1.3,
    carbs_per_100g: 28.5,
    fat_per_100g: 0.3,
    fiber_per_100g: 2.3,
    default_serving_g: 180,
    default_serving_label: '1 whole plantain',
  }, // estimate
  {
    slug: 'bole-fish',
    name: 'Bole + Fish Combo',
    category: 'nigerian',
    tags: ['street', 'nigerian', 'combo'],
    kcal_per_100g: 150,
    protein_per_100g: 10.0,
    carbs_per_100g: 18.0,
    fat_per_100g: 4.0,
    fiber_per_100g: 1.5,
    default_serving_g: 300,
    default_serving_label: '1 plate',
  }, // estimate — grilled plantain plus fish
  {
    slug: 'abacha',
    name: 'Abacha (African Salad)',
    category: 'nigerian',
    tags: ['nigerian', 'igbo', 'salad'],
    kcal_per_100g: 220,
    protein_per_100g: 5.5,
    carbs_per_100g: 22.0,
    fat_per_100g: 12.5,
    fiber_per_100g: 3.5,
    default_serving_g: 200,
    default_serving_label: '1 plate',
  }, // estimate — palm oil, ugba, fish
  {
    slug: 'nigerian-salad',
    name: 'Nigerian Salad',
    category: 'nigerian',
    tags: ['nigerian', 'salad', 'side'],
    kcal_per_100g: 130,
    protein_per_100g: 4.0,
    carbs_per_100g: 10.0,
    fat_per_100g: 8.0,
    fiber_per_100g: 2.0,
    default_serving_g: 200,
    default_serving_label: '1 serving',
  }, // estimate — with boiled egg, baked beans, salad cream
  {
    slug: 'egg-sauce',
    name: 'Egg Sauce (Nigerian)',
    category: 'nigerian',
    tags: ['nigerian', 'protein', 'breakfast'],
    kcal_per_100g: 160,
    protein_per_100g: 9.0,
    carbs_per_100g: 4.0,
    fat_per_100g: 12.0,
    fiber_per_100g: 0.8,
    default_serving_g: 150,
    default_serving_label: '1 serving',
  }, // estimate
  {
    slug: 'plantain-moi-moi',
    name: 'Plantain Moi Moi',
    category: 'nigerian',
    tags: ['nigerian', 'plantain', 'bean'],
    kcal_per_100g: 170,
    protein_per_100g: 8.5,
    carbs_per_100g: 18.0,
    fat_per_100g: 7.0,
    fiber_per_100g: 3.5,
    default_serving_g: 120,
    default_serving_label: '1 wrap',
  }, // estimate
  {
    slug: 'jollof-spaghetti',
    name: 'Jollof Spaghetti',
    category: 'nigerian',
    tags: ['nigerian', 'pasta', 'carb'],
    kcal_per_100g: 170,
    protein_per_100g: 5.5,
    carbs_per_100g: 27.0,
    fat_per_100g: 4.5,
    fiber_per_100g: 1.5,
    default_serving_g: 300,
    default_serving_label: '1 plate',
  }, // estimate

  // ============================================================
  // GLOBAL BASICS (~80)
  // ============================================================

  // --- Proteins ---
  {
    slug: 'chicken-breast',
    name: 'Chicken Breast (cooked, skinless)',
    category: 'global',
    tags: ['protein', 'lean', 'global', 'meat', 'poultry'],
    kcal_per_100g: 165,
    protein_per_100g: 31,
    carbs_per_100g: 0,
    fat_per_100g: 4.6,
    fiber_per_100g: 0,
    default_serving_g: 120,
    default_serving_label: '1 medium breast',
  }, // USDA
  {
    slug: 'chicken-thigh-cooked',
    name: 'Chicken Thigh (cooked, skinless)',
    category: 'global',
    tags: ['protein', 'global', 'meat', 'poultry'],
    kcal_per_100g: 209,
    protein_per_100g: 26,
    carbs_per_100g: 0,
    fat_per_100g: 11.7,
    fiber_per_100g: 0,
    default_serving_g: 120,
    default_serving_label: '1 thigh',
  }, // USDA
  {
    slug: 'salmon-cooked',
    name: 'Salmon (cooked, Atlantic)',
    category: 'global',
    tags: ['protein', 'global', 'fish', 'omega3'],
    kcal_per_100g: 206,
    protein_per_100g: 22.0,
    carbs_per_100g: 0,
    fat_per_100g: 13.0,
    fiber_per_100g: 0,
    default_serving_g: 120,
    default_serving_label: '1 fillet',
  }, // USDA
  {
    slug: 'tuna-canned-water',
    name: 'Tuna (canned in water, drained)',
    category: 'global',
    tags: ['protein', 'global', 'fish', 'lean'],
    kcal_per_100g: 116,
    protein_per_100g: 25.5,
    carbs_per_100g: 0,
    fat_per_100g: 1.0,
    fiber_per_100g: 0,
    default_serving_g: 85,
    default_serving_label: '1 small can',
  }, // USDA
  {
    slug: 'egg-whole',
    name: 'Whole Egg',
    category: 'global',
    tags: ['protein', 'global', 'egg', 'breakfast'],
    kcal_per_100g: 143,
    protein_per_100g: 12.6,
    carbs_per_100g: 0.7,
    fat_per_100g: 9.5,
    fiber_per_100g: 0,
    default_serving_g: 50,
    default_serving_label: '1 large egg',
  }, // USDA
  {
    slug: 'egg-white',
    name: 'Egg White',
    category: 'global',
    tags: ['protein', 'global', 'egg', 'lean'],
    kcal_per_100g: 52,
    protein_per_100g: 11.0,
    carbs_per_100g: 0.7,
    fat_per_100g: 0.2,
    fiber_per_100g: 0,
    default_serving_g: 33,
    default_serving_label: '1 egg white',
  }, // USDA
  {
    slug: 'greek-yogurt-plain-full',
    name: 'Greek Yogurt (plain, full-fat)',
    category: 'global',
    tags: ['protein', 'global', 'dairy', 'breakfast'],
    kcal_per_100g: 97,
    protein_per_100g: 9.0,
    carbs_per_100g: 4.0,
    fat_per_100g: 5.0,
    fiber_per_100g: 0,
    default_serving_g: 170,
    default_serving_label: '1 single-serve cup',
  }, // USDA
  {
    slug: 'greek-yogurt-nonfat',
    name: 'Greek Yogurt (non-fat)',
    category: 'global',
    tags: ['protein', 'global', 'dairy', 'lean', 'breakfast'],
    kcal_per_100g: 59,
    protein_per_100g: 10.2,
    carbs_per_100g: 3.6,
    fat_per_100g: 0.4,
    fiber_per_100g: 0,
    default_serving_g: 170,
    default_serving_label: '1 single-serve cup',
  }, // USDA
  {
    slug: 'cottage-cheese',
    name: 'Cottage Cheese (low-fat 2%)',
    category: 'global',
    tags: ['protein', 'global', 'dairy'],
    kcal_per_100g: 84,
    protein_per_100g: 11.0,
    carbs_per_100g: 4.3,
    fat_per_100g: 2.3,
    fiber_per_100g: 0,
    default_serving_g: 120,
    default_serving_label: '1/2 cup',
  }, // USDA
  {
    slug: 'whey-protein-powder',
    name: 'Whey Protein Powder',
    category: 'global',
    tags: ['protein', 'supplement', 'global', 'powder'],
    kcal_per_100g: 400,
    protein_per_100g: 80,
    carbs_per_100g: 7,
    fat_per_100g: 6,
    fiber_per_100g: 0,
    default_serving_g: 30,
    default_serving_label: '1 scoop (30 g)',
  }, // estimate — typical whey concentrate
  {
    slug: 'ground-beef-85',
    name: 'Ground Beef 85/15 (cooked)',
    category: 'global',
    tags: ['protein', 'global', 'meat', 'beef'],
    kcal_per_100g: 250,
    protein_per_100g: 26.0,
    carbs_per_100g: 0,
    fat_per_100g: 16.0,
    fiber_per_100g: 0,
    default_serving_g: 120,
    default_serving_label: '1 patty',
  }, // USDA
  {
    slug: 'ground-beef-93',
    name: 'Ground Beef 93/7 (cooked)',
    category: 'global',
    tags: ['protein', 'global', 'meat', 'beef', 'lean'],
    kcal_per_100g: 180,
    protein_per_100g: 27.0,
    carbs_per_100g: 0,
    fat_per_100g: 8.0,
    fiber_per_100g: 0,
    default_serving_g: 120,
    default_serving_label: '1 patty',
  }, // USDA
  {
    slug: 'turkey-breast-cooked',
    name: 'Turkey Breast (cooked, skinless)',
    category: 'global',
    tags: ['protein', 'global', 'meat', 'poultry', 'lean'],
    kcal_per_100g: 135,
    protein_per_100g: 30.0,
    carbs_per_100g: 0,
    fat_per_100g: 1.5,
    fiber_per_100g: 0,
    default_serving_g: 120,
    default_serving_label: '1 serving',
  }, // USDA
  {
    slug: 'tofu-firm',
    name: 'Tofu (firm)',
    category: 'global',
    tags: ['protein', 'global', 'vegan', 'soy'],
    kcal_per_100g: 144,
    protein_per_100g: 17,
    carbs_per_100g: 2,
    fat_per_100g: 8,
    fiber_per_100g: 2.3,
    default_serving_g: 150,
    default_serving_label: '1 serving',
  }, // USDA
  {
    slug: 'tempeh',
    name: 'Tempeh',
    category: 'global',
    tags: ['protein', 'global', 'vegan', 'soy'],
    kcal_per_100g: 192,
    protein_per_100g: 20.3,
    carbs_per_100g: 3.4,
    fat_per_100g: 10.8,
    fiber_per_100g: 0,
    default_serving_g: 120,
    default_serving_label: '1 serving',
  }, // USDA
  {
    slug: 'sardines-oil-drained',
    name: 'Sardines (canned in oil, drained)',
    category: 'global',
    tags: ['protein', 'global', 'fish', 'omega3'],
    kcal_per_100g: 208,
    protein_per_100g: 25.0,
    carbs_per_100g: 0,
    fat_per_100g: 11.5,
    fiber_per_100g: 0,
    default_serving_g: 90,
    default_serving_label: '1 small tin',
  }, // USDA
  {
    slug: 'mackerel-cooked',
    name: 'Mackerel (cooked)',
    category: 'global',
    tags: ['protein', 'global', 'fish', 'omega3'],
    kcal_per_100g: 262,
    protein_per_100g: 24.0,
    carbs_per_100g: 0,
    fat_per_100g: 18.0,
    fiber_per_100g: 0,
    default_serving_g: 120,
    default_serving_label: '1 fillet',
  }, // USDA
  {
    slug: 'shrimp-cooked',
    name: 'Shrimp (cooked)',
    category: 'global',
    tags: ['protein', 'global', 'seafood', 'lean'],
    kcal_per_100g: 99,
    protein_per_100g: 24.0,
    carbs_per_100g: 0.2,
    fat_per_100g: 0.3,
    fiber_per_100g: 0,
    default_serving_g: 100,
    default_serving_label: '1 serving',
  }, // USDA
  {
    slug: 'beef-steak-lean',
    name: 'Beef Steak (lean, grilled)',
    category: 'global',
    tags: ['protein', 'global', 'meat', 'beef'],
    kcal_per_100g: 220,
    protein_per_100g: 29.0,
    carbs_per_100g: 0,
    fat_per_100g: 11.0,
    fiber_per_100g: 0,
    default_serving_g: 150,
    default_serving_label: '1 steak',
  }, // USDA
  {
    slug: 'pork-tenderloin',
    name: 'Pork Tenderloin (cooked)',
    category: 'global',
    tags: ['protein', 'global', 'meat', 'pork', 'lean'],
    kcal_per_100g: 170,
    protein_per_100g: 29.0,
    carbs_per_100g: 0,
    fat_per_100g: 5.5,
    fiber_per_100g: 0,
    default_serving_g: 120,
    default_serving_label: '1 serving',
  }, // USDA
  {
    slug: 'milk-skim',
    name: 'Milk (skim)',
    category: 'global',
    tags: ['protein', 'global', 'dairy', 'beverage'],
    kcal_per_100g: 34,
    protein_per_100g: 3.4,
    carbs_per_100g: 5.0,
    fat_per_100g: 0.1,
    fiber_per_100g: 0,
    default_serving_g: 240,
    default_serving_label: '1 cup',
  }, // USDA
  {
    slug: 'milk-whole',
    name: 'Milk (whole, 3.25%)',
    category: 'global',
    tags: ['protein', 'global', 'dairy', 'beverage'],
    kcal_per_100g: 61,
    protein_per_100g: 3.2,
    carbs_per_100g: 4.8,
    fat_per_100g: 3.3,
    fiber_per_100g: 0,
    default_serving_g: 240,
    default_serving_label: '1 cup',
  }, // USDA

  // --- Carbs ---
  {
    slug: 'oats-rolled-dry',
    name: 'Oats (rolled, dry)',
    category: 'global',
    tags: ['carb', 'global', 'grain', 'breakfast'],
    kcal_per_100g: 379,
    protein_per_100g: 13.2,
    carbs_per_100g: 67.7,
    fat_per_100g: 6.5,
    fiber_per_100g: 10.1,
    default_serving_g: 40,
    default_serving_label: '1/2 cup dry',
  }, // USDA
  {
    slug: 'oatmeal-cooked',
    name: 'Oatmeal (cooked with water)',
    category: 'global',
    tags: ['carb', 'global', 'grain', 'breakfast'],
    kcal_per_100g: 68,
    protein_per_100g: 2.4,
    carbs_per_100g: 12.0,
    fat_per_100g: 1.4,
    fiber_per_100g: 1.7,
    default_serving_g: 230,
    default_serving_label: '1 bowl',
  }, // USDA
  {
    slug: 'brown-rice-cooked',
    name: 'Brown Rice (cooked)',
    category: 'global',
    tags: ['carb', 'global', 'grain', 'rice'],
    kcal_per_100g: 123,
    protein_per_100g: 2.7,
    carbs_per_100g: 25.6,
    fat_per_100g: 1.0,
    fiber_per_100g: 1.6,
    default_serving_g: 150,
    default_serving_label: '1 cup cooked',
  }, // USDA
  {
    slug: 'white-rice-cooked',
    name: 'White Rice (cooked, long-grain)',
    category: 'global',
    tags: ['carb', 'global', 'grain', 'rice'],
    kcal_per_100g: 130,
    protein_per_100g: 2.7,
    carbs_per_100g: 28.2,
    fat_per_100g: 0.3,
    fiber_per_100g: 0.4,
    default_serving_g: 150,
    default_serving_label: '1 cup cooked',
  }, // USDA
  {
    slug: 'pasta-cooked',
    name: 'Pasta (cooked, regular)',
    category: 'global',
    tags: ['carb', 'global', 'grain', 'pasta'],
    kcal_per_100g: 157,
    protein_per_100g: 5.8,
    carbs_per_100g: 30.6,
    fat_per_100g: 0.9,
    fiber_per_100g: 1.8,
    default_serving_g: 180,
    default_serving_label: '1 cup cooked',
  }, // USDA
  {
    slug: 'pasta-whole-wheat',
    name: 'Pasta (whole wheat, cooked)',
    category: 'global',
    tags: ['carb', 'global', 'grain', 'pasta', 'fiber'],
    kcal_per_100g: 149,
    protein_per_100g: 6,
    carbs_per_100g: 29,
    fat_per_100g: 1.3,
    fiber_per_100g: 4.5,
    default_serving_g: 180,
    default_serving_label: '1 cup cooked',
  }, // USDA
  {
    slug: 'bread-whole-wheat',
    name: 'Bread (whole wheat)',
    category: 'global',
    tags: ['carb', 'global', 'grain', 'bread', 'fiber'],
    kcal_per_100g: 247,
    protein_per_100g: 13.0,
    carbs_per_100g: 41.0,
    fat_per_100g: 3.4,
    fiber_per_100g: 7.0,
    default_serving_g: 30,
    default_serving_label: '1 slice',
  }, // USDA
  {
    slug: 'bread-white',
    name: 'Bread (white)',
    category: 'global',
    tags: ['carb', 'global', 'grain', 'bread'],
    kcal_per_100g: 265,
    protein_per_100g: 9.0,
    carbs_per_100g: 49.0,
    fat_per_100g: 3.2,
    fiber_per_100g: 2.3,
    default_serving_g: 28,
    default_serving_label: '1 slice',
  }, // USDA
  {
    slug: 'sweet-potato-cooked',
    name: 'Sweet Potato (cooked)',
    category: 'global',
    tags: ['carb', 'global', 'tuber'],
    kcal_per_100g: 90,
    protein_per_100g: 2.0,
    carbs_per_100g: 20.7,
    fat_per_100g: 0.2,
    fiber_per_100g: 3.3,
    default_serving_g: 150,
    default_serving_label: '1 medium',
  }, // USDA
  {
    slug: 'white-potato-cooked',
    name: 'White Potato (cooked, boiled)',
    category: 'global',
    tags: ['carb', 'global', 'tuber'],
    kcal_per_100g: 87,
    protein_per_100g: 1.9,
    carbs_per_100g: 20.1,
    fat_per_100g: 0.1,
    fiber_per_100g: 1.8,
    default_serving_g: 150,
    default_serving_label: '1 medium',
  }, // USDA
  {
    slug: 'quinoa-cooked',
    name: 'Quinoa (cooked)',
    category: 'global',
    tags: ['carb', 'global', 'grain', 'protein'],
    kcal_per_100g: 120,
    protein_per_100g: 4.4,
    carbs_per_100g: 21.3,
    fat_per_100g: 1.9,
    fiber_per_100g: 2.8,
    default_serving_g: 150,
    default_serving_label: '1 cup cooked',
  }, // USDA
  {
    slug: 'lentils-cooked',
    name: 'Lentils (cooked)',
    category: 'global',
    tags: ['carb', 'global', 'legume', 'protein', 'fiber'],
    kcal_per_100g: 116,
    protein_per_100g: 9.0,
    carbs_per_100g: 20.1,
    fat_per_100g: 0.4,
    fiber_per_100g: 7.9,
    default_serving_g: 150,
    default_serving_label: '1 cup cooked',
  }, // USDA
  {
    slug: 'black-beans-cooked',
    name: 'Black Beans (cooked)',
    category: 'global',
    tags: ['carb', 'global', 'legume', 'protein', 'fiber'],
    kcal_per_100g: 132,
    protein_per_100g: 8.9,
    carbs_per_100g: 23.7,
    fat_per_100g: 0.5,
    fiber_per_100g: 8.7,
    default_serving_g: 150,
    default_serving_label: '1 cup cooked',
  }, // USDA
  {
    slug: 'chickpeas-cooked',
    name: 'Chickpeas (cooked)',
    category: 'global',
    tags: ['carb', 'global', 'legume', 'protein', 'fiber'],
    kcal_per_100g: 164,
    protein_per_100g: 8.9,
    carbs_per_100g: 27.4,
    fat_per_100g: 2.6,
    fiber_per_100g: 7.6,
    default_serving_g: 150,
    default_serving_label: '1 cup cooked',
  }, // USDA
  {
    slug: 'pita-bread',
    name: 'Pita Bread (white)',
    category: 'global',
    tags: ['carb', 'global', 'grain', 'bread'],
    kcal_per_100g: 275,
    protein_per_100g: 9.1,
    carbs_per_100g: 55.7,
    fat_per_100g: 1.2,
    fiber_per_100g: 2.2,
    default_serving_g: 60,
    default_serving_label: '1 pita',
  }, // USDA
  {
    slug: 'tortilla-flour',
    name: 'Tortilla (flour)',
    category: 'global',
    tags: ['carb', 'global', 'bread'],
    kcal_per_100g: 306,
    protein_per_100g: 8.2,
    carbs_per_100g: 50.0,
    fat_per_100g: 7.6,
    fiber_per_100g: 3.0,
    default_serving_g: 50,
    default_serving_label: '1 medium tortilla',
  }, // USDA
  {
    slug: 'couscous-cooked',
    name: 'Couscous (cooked)',
    category: 'global',
    tags: ['carb', 'global', 'grain'],
    kcal_per_100g: 112,
    protein_per_100g: 3.8,
    carbs_per_100g: 23.2,
    fat_per_100g: 0.2,
    fiber_per_100g: 1.4,
    default_serving_g: 150,
    default_serving_label: '1 cup cooked',
  }, // USDA

  // --- Fats ---
  {
    slug: 'olive-oil',
    name: 'Olive Oil',
    category: 'global',
    tags: ['fat', 'global', 'oil'],
    kcal_per_100g: 884,
    protein_per_100g: 0,
    carbs_per_100g: 0,
    fat_per_100g: 98,
    fiber_per_100g: 0,
    default_serving_g: 14,
    default_serving_label: '1 tbsp',
  }, // USDA — energy = 9 × 100 ≈ 900, USDA lists 884 (rounding convention)
  {
    slug: 'coconut-oil',
    name: 'Coconut Oil',
    category: 'global',
    tags: ['fat', 'global', 'oil'],
    kcal_per_100g: 892,
    protein_per_100g: 0,
    carbs_per_100g: 0,
    fat_per_100g: 99.1,
    fiber_per_100g: 0,
    default_serving_g: 14,
    default_serving_label: '1 tbsp',
  }, // USDA — matches 9×99.1
  {
    slug: 'avocado',
    name: 'Avocado',
    category: 'global',
    tags: ['fat', 'global', 'fruit'],
    kcal_per_100g: 160,
    protein_per_100g: 2,
    carbs_per_100g: 5.5,
    fat_per_100g: 14.7,
    fiber_per_100g: 6.7,
    default_serving_g: 100,
    default_serving_label: '1/2 medium avocado',
  }, // USDA
  {
    slug: 'almonds',
    name: 'Almonds',
    category: 'global',
    tags: ['fat', 'global', 'nuts', 'snack'],
    kcal_per_100g: 579,
    protein_per_100g: 21.2,
    carbs_per_100g: 11.3,
    fat_per_100g: 49.9,
    fiber_per_100g: 12.5,
    default_serving_g: 28,
    default_serving_label: '1 small handful (23 nuts)',
  }, // USDA
  {
    slug: 'walnuts',
    name: 'Walnuts',
    category: 'global',
    tags: ['fat', 'global', 'nuts', 'snack', 'omega3'],
    kcal_per_100g: 654,
    protein_per_100g: 15.2,
    carbs_per_100g: 13.7,
    fat_per_100g: 59.8,
    fiber_per_100g: 6.7,
    default_serving_g: 28,
    default_serving_label: '1 small handful',
  }, // USDA
  {
    slug: 'peanut-butter',
    name: 'Peanut Butter (natural)',
    category: 'global',
    tags: ['fat', 'global', 'nuts', 'spread'],
    kcal_per_100g: 590,
    protein_per_100g: 25,
    carbs_per_100g: 16.8,
    fat_per_100g: 47,
    fiber_per_100g: 6.0,
    default_serving_g: 16,
    default_serving_label: '1 tbsp',
  }, // USDA
  {
    slug: 'mixed-nuts',
    name: 'Mixed Nuts (dry roasted)',
    category: 'global',
    tags: ['fat', 'global', 'nuts', 'snack'],
    kcal_per_100g: 607,
    protein_per_100g: 20,
    carbs_per_100g: 21.1,
    fat_per_100g: 49.2,
    fiber_per_100g: 7.0,
    default_serving_g: 28,
    default_serving_label: '1 small handful',
  }, // USDA
  {
    slug: 'cheddar-cheese',
    name: 'Cheddar Cheese',
    category: 'global',
    tags: ['fat', 'global', 'dairy', 'cheese'],
    kcal_per_100g: 403,
    protein_per_100g: 25.0,
    carbs_per_100g: 1.3,
    fat_per_100g: 33.0,
    fiber_per_100g: 0,
    default_serving_g: 28,
    default_serving_label: '1 slice',
  }, // USDA
  {
    slug: 'feta-cheese',
    name: 'Feta Cheese',
    category: 'global',
    tags: ['fat', 'global', 'dairy', 'cheese'],
    kcal_per_100g: 264,
    protein_per_100g: 14.2,
    carbs_per_100g: 4.1,
    fat_per_100g: 21.3,
    fiber_per_100g: 0,
    default_serving_g: 30,
    default_serving_label: '1 small portion',
  }, // USDA
  {
    slug: 'butter',
    name: 'Butter',
    category: 'global',
    tags: ['fat', 'global', 'dairy'],
    kcal_per_100g: 717,
    protein_per_100g: 0.9,
    carbs_per_100g: 0.1,
    fat_per_100g: 79.5,
    fiber_per_100g: 0,
    default_serving_g: 14,
    default_serving_label: '1 tbsp',
  }, // USDA
  {
    slug: 'tahini',
    name: 'Tahini',
    category: 'global',
    tags: ['fat', 'global', 'spread'],
    kcal_per_100g: 595,
    protein_per_100g: 17,
    carbs_per_100g: 10.7,
    fat_per_100g: 53.8,
    fiber_per_100g: 9.3,
    default_serving_g: 15,
    default_serving_label: '1 tbsp',
  }, // USDA
  {
    slug: 'dark-chocolate-70',
    name: 'Dark Chocolate (70%)',
    category: 'global',
    tags: ['fat', 'global', 'snack', 'sweet'],
    kcal_per_100g: 598,
    protein_per_100g: 7.8,
    carbs_per_100g: 46.0,
    fat_per_100g: 42.6,
    fiber_per_100g: 11.0,
    default_serving_g: 25,
    default_serving_label: '2 squares',
  }, // USDA

  // --- Fruits ---
  {
    slug: 'banana',
    name: 'Banana',
    category: 'global',
    tags: ['fruit', 'global', 'carb'],
    kcal_per_100g: 89,
    protein_per_100g: 1.1,
    carbs_per_100g: 20.2,
    fat_per_100g: 0.3,
    fiber_per_100g: 2.6,
    default_serving_g: 118,
    default_serving_label: '1 medium banana',
  }, // USDA
  {
    slug: 'apple',
    name: 'Apple',
    category: 'global',
    tags: ['fruit', 'global'],
    kcal_per_100g: 52,
    protein_per_100g: 0.3,
    carbs_per_100g: 12.5,
    fat_per_100g: 0.2,
    fiber_per_100g: 2.4,
    default_serving_g: 180,
    default_serving_label: '1 medium apple',
  }, // USDA
  {
    slug: 'orange',
    name: 'Orange',
    category: 'global',
    tags: ['fruit', 'global', 'citrus'],
    kcal_per_100g: 47,
    protein_per_100g: 0.9,
    carbs_per_100g: 11.8,
    fat_per_100g: 0.1,
    fiber_per_100g: 2.4,
    default_serving_g: 131,
    default_serving_label: '1 medium orange',
  }, // USDA
  {
    slug: 'pineapple',
    name: 'Pineapple',
    category: 'global',
    tags: ['fruit', 'global', 'tropical'],
    kcal_per_100g: 50,
    protein_per_100g: 0.5,
    carbs_per_100g: 11.8,
    fat_per_100g: 0.1,
    fiber_per_100g: 1.4,
    default_serving_g: 165,
    default_serving_label: '1 cup chunks',
  }, // USDA
  {
    slug: 'mango',
    name: 'Mango',
    category: 'global',
    tags: ['fruit', 'global', 'tropical'],
    kcal_per_100g: 60,
    protein_per_100g: 0.8,
    carbs_per_100g: 13.7,
    fat_per_100g: 0.4,
    fiber_per_100g: 1.6,
    default_serving_g: 165,
    default_serving_label: '1 cup sliced',
  }, // USDA
  {
    slug: 'watermelon',
    name: 'Watermelon',
    category: 'global',
    tags: ['fruit', 'global'],
    kcal_per_100g: 30,
    protein_per_100g: 0.6,
    carbs_per_100g: 7.6,
    fat_per_100g: 0.2,
    fiber_per_100g: 0.4,
    default_serving_g: 150,
    default_serving_label: '1 cup diced',
  }, // USDA
  {
    slug: 'mixed-berries',
    name: 'Mixed Berries',
    category: 'global',
    tags: ['fruit', 'global', 'berry'],
    kcal_per_100g: 50,
    protein_per_100g: 0.8,
    carbs_per_100g: 12.0,
    fat_per_100g: 0.3,
    fiber_per_100g: 3.0,
    default_serving_g: 100,
    default_serving_label: '1 cup',
  }, // estimate — blend of blueberry/strawberry/raspberry
  {
    slug: 'dates',
    name: 'Dates (Medjool)',
    category: 'global',
    tags: ['fruit', 'global', 'dried', 'sweet'],
    kcal_per_100g: 277,
    protein_per_100g: 1.8,
    carbs_per_100g: 66.5,
    fat_per_100g: 0.2,
    fiber_per_100g: 6.7,
    default_serving_g: 24,
    default_serving_label: '1 medjool date',
  }, // USDA
  {
    slug: 'pear',
    name: 'Pear',
    category: 'global',
    tags: ['fruit', 'global'],
    kcal_per_100g: 57,
    protein_per_100g: 0.4,
    carbs_per_100g: 13.8,
    fat_per_100g: 0.1,
    fiber_per_100g: 3.1,
    default_serving_g: 178,
    default_serving_label: '1 medium pear',
  }, // USDA
  {
    slug: 'grapes',
    name: 'Grapes',
    category: 'global',
    tags: ['fruit', 'global'],
    kcal_per_100g: 69,
    protein_per_100g: 0.7,
    carbs_per_100g: 16.5,
    fat_per_100g: 0.2,
    fiber_per_100g: 0.9,
    default_serving_g: 150,
    default_serving_label: '1 cup',
  }, // USDA

  // --- Vegetables ---
  {
    slug: 'broccoli',
    name: 'Broccoli (raw)',
    category: 'global',
    tags: ['vegetable', 'global', 'greens'],
    kcal_per_100g: 34,
    protein_per_100g: 2.8,
    carbs_per_100g: 4.8,
    fat_per_100g: 0.4,
    fiber_per_100g: 2.6,
    default_serving_g: 90,
    default_serving_label: '1 cup florets',
  }, // USDA
  {
    slug: 'spinach-raw',
    name: 'Spinach (raw)',
    category: 'global',
    tags: ['vegetable', 'global', 'greens'],
    kcal_per_100g: 23,
    protein_per_100g: 2.9,
    carbs_per_100g: 2,
    fat_per_100g: 0.4,
    fiber_per_100g: 2.2,
    default_serving_g: 30,
    default_serving_label: '1 cup raw',
  }, // USDA
  {
    slug: 'tomato',
    name: 'Tomato',
    category: 'global',
    tags: ['vegetable', 'global'],
    kcal_per_100g: 18,
    protein_per_100g: 0.9,
    carbs_per_100g: 3.9,
    fat_per_100g: 0.2,
    fiber_per_100g: 1.2,
    default_serving_g: 123,
    default_serving_label: '1 medium tomato',
  }, // USDA
  {
    slug: 'cucumber',
    name: 'Cucumber',
    category: 'global',
    tags: ['vegetable', 'global'],
    kcal_per_100g: 16,
    protein_per_100g: 0.7,
    carbs_per_100g: 3.6,
    fat_per_100g: 0.1,
    fiber_per_100g: 0.5,
    default_serving_g: 100,
    default_serving_label: '1 cup sliced',
  }, // USDA
  {
    slug: 'bell-pepper',
    name: 'Bell Pepper (red)',
    category: 'global',
    tags: ['vegetable', 'global'],
    kcal_per_100g: 31,
    protein_per_100g: 1.0,
    carbs_per_100g: 6.0,
    fat_per_100g: 0.3,
    fiber_per_100g: 2.1,
    default_serving_g: 120,
    default_serving_label: '1 medium pepper',
  }, // USDA
  {
    slug: 'carrot',
    name: 'Carrot (raw)',
    category: 'global',
    tags: ['vegetable', 'global'],
    kcal_per_100g: 41,
    protein_per_100g: 0.9,
    carbs_per_100g: 9.6,
    fat_per_100g: 0.2,
    fiber_per_100g: 2.8,
    default_serving_g: 61,
    default_serving_label: '1 medium carrot',
  }, // USDA
  {
    slug: 'cabbage',
    name: 'Cabbage (raw)',
    category: 'global',
    tags: ['vegetable', 'global'],
    kcal_per_100g: 25,
    protein_per_100g: 1.3,
    carbs_per_100g: 5.8,
    fat_per_100g: 0.1,
    fiber_per_100g: 2.5,
    default_serving_g: 89,
    default_serving_label: '1 cup shredded',
  }, // USDA
  {
    slug: 'kale',
    name: 'Kale (raw)',
    category: 'global',
    tags: ['vegetable', 'global', 'greens'],
    kcal_per_100g: 35,
    protein_per_100g: 2.9,
    carbs_per_100g: 3,
    fat_per_100g: 1.5,
    fiber_per_100g: 4.1,
    default_serving_g: 67,
    default_serving_label: '1 cup chopped',
  }, // USDA
  {
    slug: 'green-beans',
    name: 'Green Beans',
    category: 'global',
    tags: ['vegetable', 'global'],
    kcal_per_100g: 31,
    protein_per_100g: 1.8,
    carbs_per_100g: 5.5,
    fat_per_100g: 0.2,
    fiber_per_100g: 3.4,
    default_serving_g: 100,
    default_serving_label: '1 cup',
  }, // USDA
  {
    slug: 'onion',
    name: 'Onion',
    category: 'global',
    tags: ['vegetable', 'global'],
    kcal_per_100g: 40,
    protein_per_100g: 1.1,
    carbs_per_100g: 9.3,
    fat_per_100g: 0.1,
    fiber_per_100g: 1.7,
    default_serving_g: 110,
    default_serving_label: '1 medium onion',
  }, // USDA
  {
    slug: 'mushrooms',
    name: 'Mushrooms (white, raw)',
    category: 'global',
    tags: ['vegetable', 'global'],
    kcal_per_100g: 22,
    protein_per_100g: 3.1,
    carbs_per_100g: 2.4,
    fat_per_100g: 0.3,
    fiber_per_100g: 1.0,
    default_serving_g: 96,
    default_serving_label: '1 cup sliced',
  }, // USDA
  {
    slug: 'zucchini',
    name: 'Zucchini',
    category: 'global',
    tags: ['vegetable', 'global'],
    kcal_per_100g: 17,
    protein_per_100g: 1.2,
    carbs_per_100g: 3.1,
    fat_per_100g: 0.3,
    fiber_per_100g: 1.0,
    default_serving_g: 124,
    default_serving_label: '1 medium zucchini',
  }, // USDA
  {
    slug: 'garlic',
    name: 'Garlic',
    category: 'global',
    tags: ['vegetable', 'global', 'flavor'],
    kcal_per_100g: 149,
    protein_per_100g: 6.4,
    carbs_per_100g: 30,
    fat_per_100g: 0.5,
    fiber_per_100g: 2.1,
    default_serving_g: 3,
    default_serving_label: '1 clove',
  }, // USDA
  {
    slug: 'sweet-corn',
    name: 'Sweet Corn (kernels, cooked)',
    category: 'global',
    tags: ['vegetable', 'global', 'carb'],
    kcal_per_100g: 96,
    protein_per_100g: 3.4,
    carbs_per_100g: 17.2,
    fat_per_100g: 1.5,
    fiber_per_100g: 2.4,
    default_serving_g: 150,
    default_serving_label: '1 cup',
  }, // USDA
  {
    slug: 'lettuce-romaine',
    name: 'Romaine Lettuce',
    category: 'global',
    tags: ['vegetable', 'global', 'greens'],
    kcal_per_100g: 17,
    protein_per_100g: 1.2,
    carbs_per_100g: 3.3,
    fat_per_100g: 0.3,
    fiber_per_100g: 2.1,
    default_serving_g: 50,
    default_serving_label: '1 cup shredded',
  }, // USDA

  // ============================================================
  // SUPPLEMENTS (~10)
  // ============================================================
  {
    slug: 'whey-isolate',
    name: 'Whey Protein Isolate',
    category: 'supplement',
    tags: ['supplement', 'protein', 'powder'],
    kcal_per_100g: 375,
    protein_per_100g: 90.0,
    carbs_per_100g: 2.0,
    fat_per_100g: 1.0,
    fiber_per_100g: 0,
    default_serving_g: 30,
    default_serving_label: '1 scoop (30 g)',
  }, // estimate — typical isolate label
  {
    slug: 'casein-protein',
    name: 'Casein Protein Powder',
    category: 'supplement',
    tags: ['supplement', 'protein', 'powder'],
    kcal_per_100g: 370,
    protein_per_100g: 80.0,
    carbs_per_100g: 7.0,
    fat_per_100g: 3.0,
    fiber_per_100g: 0,
    default_serving_g: 32,
    default_serving_label: '1 scoop (32 g)',
  }, // estimate — typical label
  {
    slug: 'creatine-monohydrate',
    name: 'Creatine Monohydrate',
    category: 'supplement',
    tags: ['supplement', 'performance'],
    kcal_per_100g: 0,
    protein_per_100g: 0,
    carbs_per_100g: 0,
    fat_per_100g: 0,
    fiber_per_100g: 0,
    default_serving_g: 5,
    default_serving_label: '1 scoop (5 g)',
  }, // label — metabolized but label lists 0 kcal
  {
    slug: 'multivitamin',
    name: 'Multivitamin Tablet',
    category: 'supplement',
    tags: ['supplement', 'micro'],
    kcal_per_100g: 0,
    protein_per_100g: 0,
    carbs_per_100g: 0,
    fat_per_100g: 0,
    fiber_per_100g: 0,
    default_serving_g: 1,
    default_serving_label: '1 tablet',
  }, // label — negligible
  {
    slug: 'vitamin-d3',
    name: 'Vitamin D3 Capsule',
    category: 'supplement',
    tags: ['supplement', 'micro', 'vitamin'],
    kcal_per_100g: 0,
    protein_per_100g: 0,
    carbs_per_100g: 0,
    fat_per_100g: 0,
    fiber_per_100g: 0,
    default_serving_g: 1,
    default_serving_label: '1 capsule',
  }, // label — negligible
  {
    slug: 'omega-3-fish-oil',
    name: 'Omega-3 Fish Oil Capsule',
    category: 'supplement',
    tags: ['supplement', 'fat', 'omega3'],
    kcal_per_100g: 900,
    protein_per_100g: 0,
    carbs_per_100g: 0,
    fat_per_100g: 100.0,
    fiber_per_100g: 0,
    default_serving_g: 1,
    default_serving_label: '1 capsule',
  }, // label — pure oil
  {
    slug: 'magnesium-glycinate',
    name: 'Magnesium Glycinate Capsule',
    category: 'supplement',
    tags: ['supplement', 'micro', 'recovery'],
    kcal_per_100g: 0,
    protein_per_100g: 0,
    carbs_per_100g: 0,
    fat_per_100g: 0,
    fiber_per_100g: 0,
    default_serving_g: 1,
    default_serving_label: '1 capsule',
  }, // label
  {
    slug: 'pre-workout',
    name: 'Pre-Workout Powder',
    category: 'supplement',
    tags: ['supplement', 'performance', 'powder'],
    kcal_per_100g: 40,
    protein_per_100g: 0,
    carbs_per_100g: 10.0,
    fat_per_100g: 0,
    fiber_per_100g: 0,
    default_serving_g: 10,
    default_serving_label: '1 scoop (10 g)',
  }, // estimate — typical label
  {
    slug: 'bcaa-powder',
    name: 'BCAA Powder',
    category: 'supplement',
    tags: ['supplement', 'amino'],
    kcal_per_100g: 400,
    protein_per_100g: 100.0,
    carbs_per_100g: 0,
    fat_per_100g: 0,
    fiber_per_100g: 0,
    default_serving_g: 7,
    default_serving_label: '1 scoop (7 g)',
  }, // label — amino acids counted as protein kcal
  {
    slug: 'mass-gainer',
    name: 'Mass Gainer Powder',
    category: 'supplement',
    tags: ['supplement', 'protein', 'carb', 'powder'],
    kcal_per_100g: 380,
    protein_per_100g: 20.0,
    carbs_per_100g: 68.0,
    fat_per_100g: 3.0,
    fiber_per_100g: 1.0,
    default_serving_g: 100,
    default_serving_label: '1 scoop (100 g)',
  }, // estimate — typical mass gainer

  // ============================================================
  // RESTAURANT / TAKEOUT (~30)
  // ============================================================
  {
    slug: 'bukka-jollof-chicken-plantain',
    name: 'Bukka Plate: Jollof + Chicken + Plantain',
    category: 'restaurant',
    tags: ['restaurant', 'nigerian', 'bukka', 'combo'],
    kcal_per_100g: 190,
    protein_per_100g: 7.5,
    carbs_per_100g: 24.0,
    fat_per_100g: 7.5,
    fiber_per_100g: 1.5,
    default_serving_g: 500,
    default_serving_label: '1 bukka plate',
  }, // estimate — typical plated combo
  {
    slug: 'bukka-rice-stew-beef',
    name: 'Bukka Plate: Rice + Stew + Beef',
    category: 'restaurant',
    tags: ['restaurant', 'nigerian', 'bukka', 'combo'],
    kcal_per_100g: 175,
    protein_per_100g: 7.0,
    carbs_per_100g: 24.0,
    fat_per_100g: 5.8,
    fiber_per_100g: 1.2,
    default_serving_g: 500,
    default_serving_label: '1 bukka plate',
  }, // estimate
  {
    slug: 'bukka-amala-ewedu-goat',
    name: 'Bukka Plate: Amala + Ewedu + Goat',
    category: 'restaurant',
    tags: ['restaurant', 'nigerian', 'bukka', 'combo'],
    kcal_per_100g: 145,
    protein_per_100g: 7.5,
    carbs_per_100g: 18.0,
    fat_per_100g: 4.8,
    fiber_per_100g: 2.0,
    default_serving_g: 500,
    default_serving_label: '1 bukka plate',
  }, // estimate
  {
    slug: 'bukka-eba-egusi-fish',
    name: 'Bukka Plate: Eba + Egusi + Fish',
    category: 'restaurant',
    tags: ['restaurant', 'nigerian', 'bukka', 'combo'],
    kcal_per_100g: 170,
    protein_per_100g: 8.0,
    carbs_per_100g: 20.0,
    fat_per_100g: 6.5,
    fiber_per_100g: 2.0,
    default_serving_g: 500,
    default_serving_label: '1 bukka plate',
  }, // estimate
  {
    slug: 'jollof-takeout-chicken',
    name: 'Jollof Takeout + Chicken',
    category: 'restaurant',
    tags: ['restaurant', 'nigerian', 'takeout'],
    kcal_per_100g: 180,
    protein_per_100g: 8.5,
    carbs_per_100g: 23.0,
    fat_per_100g: 6.5,
    fiber_per_100g: 1.2,
    default_serving_g: 450,
    default_serving_label: '1 takeout pack',
  }, // estimate
  {
    slug: 'suya-takeout-pack',
    name: 'Suya Takeout Pack',
    category: 'restaurant',
    tags: ['restaurant', 'nigerian', 'takeout', 'street'],
    kcal_per_100g: 235,
    protein_per_100g: 26.0,
    carbs_per_100g: 3.5,
    fat_per_100g: 13.0,
    fiber_per_100g: 1.0,
    default_serving_g: 250,
    default_serving_label: '1 takeout pack',
  }, // estimate — 3 sticks plus onions
  {
    slug: 'shawarma-chicken',
    name: 'Shawarma (Chicken, restaurant)',
    category: 'restaurant',
    tags: ['restaurant', 'wrap'],
    kcal_per_100g: 245,
    protein_per_100g: 13.0,
    carbs_per_100g: 20.0,
    fat_per_100g: 12.5,
    fiber_per_100g: 1.5,
    default_serving_g: 300,
    default_serving_label: '1 regular shawarma',
  }, // estimate
  {
    slug: 'shawarma-beef',
    name: 'Shawarma (Beef, restaurant)',
    category: 'restaurant',
    tags: ['restaurant', 'wrap'],
    kcal_per_100g: 265,
    protein_per_100g: 12.5,
    carbs_per_100g: 20.0,
    fat_per_100g: 15.0,
    fiber_per_100g: 1.5,
    default_serving_g: 300,
    default_serving_label: '1 regular shawarma',
  }, // estimate
  {
    slug: 'pizza-pepperoni-slice',
    name: 'Pizza (pepperoni, restaurant slice)',
    category: 'restaurant',
    tags: ['restaurant', 'pizza'],
    kcal_per_100g: 298,
    protein_per_100g: 12.5,
    carbs_per_100g: 30,
    fat_per_100g: 14.2,
    fiber_per_100g: 2.2,
    default_serving_g: 110,
    default_serving_label: '1 slice',
  }, // USDA
  {
    slug: 'pizza-margherita-slice',
    name: 'Pizza (margherita, restaurant slice)',
    category: 'restaurant',
    tags: ['restaurant', 'pizza'],
    kcal_per_100g: 250,
    protein_per_100g: 10.5,
    carbs_per_100g: 30.0,
    fat_per_100g: 9.5,
    fiber_per_100g: 2.0,
    default_serving_g: 110,
    default_serving_label: '1 slice',
  }, // USDA
  {
    slug: 'burger-beef-regular',
    name: 'Beef Burger (regular, QSR)',
    category: 'restaurant',
    tags: ['restaurant', 'burger'],
    kcal_per_100g: 260,
    protein_per_100g: 13.0,
    carbs_per_100g: 24.0,
    fat_per_100g: 12.0,
    fiber_per_100g: 1.5,
    default_serving_g: 170,
    default_serving_label: '1 regular burger',
  }, // USDA
  {
    slug: 'fries-medium',
    name: 'French Fries (medium, QSR)',
    category: 'restaurant',
    tags: ['restaurant', 'fried', 'side'],
    kcal_per_100g: 312,
    protein_per_100g: 3.4,
    carbs_per_100g: 41.0,
    fat_per_100g: 15.0,
    fiber_per_100g: 3.8,
    default_serving_g: 115,
    default_serving_label: '1 medium fries',
  }, // USDA
  {
    slug: 'fried-chicken-qsr',
    name: 'Fried Chicken (QSR, bone-in)',
    category: 'restaurant',
    tags: ['restaurant', 'fried', 'poultry'],
    kcal_per_100g: 260,
    protein_per_100g: 22.0,
    carbs_per_100g: 8.0,
    fat_per_100g: 15.0,
    fiber_per_100g: 0.5,
    default_serving_g: 150,
    default_serving_label: '1 piece',
  }, // USDA
  {
    slug: 'chinese-fried-rice',
    name: 'Chinese Fried Rice (restaurant)',
    category: 'restaurant',
    tags: ['restaurant', 'rice'],
    kcal_per_100g: 186,
    protein_per_100g: 5.5,
    carbs_per_100g: 27.0,
    fat_per_100g: 6.0,
    fiber_per_100g: 1.2,
    default_serving_g: 300,
    default_serving_label: '1 plate',
  }, // USDA
  {
    slug: 'chinese-sweet-sour-chicken',
    name: 'Sweet & Sour Chicken (restaurant)',
    category: 'restaurant',
    tags: ['restaurant', 'chinese'],
    kcal_per_100g: 205,
    protein_per_100g: 10.5,
    carbs_per_100g: 20.0,
    fat_per_100g: 9.0,
    fiber_per_100g: 0.8,
    default_serving_g: 300,
    default_serving_label: '1 plate',
  }, // estimate
  {
    slug: 'sub-sandwich-chicken',
    name: '6" Sub Sandwich (chicken)',
    category: 'restaurant',
    tags: ['restaurant', 'sandwich'],
    kcal_per_100g: 180,
    protein_per_100g: 11.5,
    carbs_per_100g: 24.0,
    fat_per_100g: 4.5,
    fiber_per_100g: 2.5,
    default_serving_g: 230,
    default_serving_label: '1 6-inch sub',
  }, // estimate
  {
    slug: 'coke-330ml',
    name: 'Coca-Cola (330 ml can)',
    category: 'restaurant',
    tags: ['restaurant', 'beverage', 'soda'],
    kcal_per_100g: 42,
    protein_per_100g: 0,
    carbs_per_100g: 10.6,
    fat_per_100g: 0,
    fiber_per_100g: 0,
    default_serving_g: 330,
    default_serving_label: '1 can (330 ml)',
  }, // label
  {
    slug: 'orange-juice-250ml',
    name: 'Orange Juice (250 ml)',
    category: 'restaurant',
    tags: ['restaurant', 'beverage', 'juice'],
    kcal_per_100g: 45,
    protein_per_100g: 0.7,
    carbs_per_100g: 10.4,
    fat_per_100g: 0.2,
    fiber_per_100g: 0.2,
    default_serving_g: 250,
    default_serving_label: '1 small glass',
  }, // USDA
  {
    slug: 'meat-pie-takeout',
    name: 'Meat Pie (takeout, large)',
    category: 'restaurant',
    tags: ['restaurant', 'nigerian', 'snack'],
    kcal_per_100g: 310,
    protein_per_100g: 8.0,
    carbs_per_100g: 30.0,
    fat_per_100g: 17.0,
    fiber_per_100g: 1.5,
    default_serving_g: 160,
    default_serving_label: '1 large meat pie',
  }, // estimate
  {
    slug: 'doughnut-glazed',
    name: 'Glazed Doughnut',
    category: 'restaurant',
    tags: ['restaurant', 'sweet', 'snack'],
    kcal_per_100g: 403,
    protein_per_100g: 4.5,
    carbs_per_100g: 45.0,
    fat_per_100g: 22.5,
    fiber_per_100g: 1.2,
    default_serving_g: 60,
    default_serving_label: '1 doughnut',
  }, // USDA
  {
    slug: 'puff-puff-takeout',
    name: 'Puff-Puff (takeout, 6-pack)',
    category: 'restaurant',
    tags: ['restaurant', 'nigerian', 'snack'],
    kcal_per_100g: 330,
    protein_per_100g: 6.0,
    carbs_per_100g: 43.0,
    fat_per_100g: 15.0,
    fiber_per_100g: 1.2,
    default_serving_g: 180,
    default_serving_label: '1 pack (6 balls)',
  }, // estimate
  {
    slug: 'pasta-alfredo-restaurant',
    name: 'Pasta Alfredo (restaurant)',
    category: 'restaurant',
    tags: ['restaurant', 'pasta', 'italian'],
    kcal_per_100g: 215,
    protein_per_100g: 7.0,
    carbs_per_100g: 25.0,
    fat_per_100g: 9.5,
    fiber_per_100g: 1.5,
    default_serving_g: 350,
    default_serving_label: '1 plate',
  }, // estimate
  {
    slug: 'pasta-bolognese-restaurant',
    name: 'Pasta Bolognese (restaurant)',
    category: 'restaurant',
    tags: ['restaurant', 'pasta', 'italian'],
    kcal_per_100g: 160,
    protein_per_100g: 8.0,
    carbs_per_100g: 20.0,
    fat_per_100g: 5.0,
    fiber_per_100g: 1.8,
    default_serving_g: 350,
    default_serving_label: '1 plate',
  }, // estimate
  {
    slug: 'caesar-salad-chicken',
    name: 'Caesar Salad with Chicken (restaurant)',
    category: 'restaurant',
    tags: ['restaurant', 'salad'],
    kcal_per_100g: 170,
    protein_per_100g: 11.0,
    carbs_per_100g: 6.0,
    fat_per_100g: 11.5,
    fiber_per_100g: 1.5,
    default_serving_g: 350,
    default_serving_label: '1 bowl',
  }, // estimate
  {
    slug: 'sushi-salmon-roll',
    name: 'Sushi (salmon roll, 8 pieces)',
    category: 'restaurant',
    tags: ['restaurant', 'sushi', 'japanese'],
    kcal_per_100g: 145,
    protein_per_100g: 6.0,
    carbs_per_100g: 22.0,
    fat_per_100g: 3.5,
    fiber_per_100g: 1.0,
    default_serving_g: 200,
    default_serving_label: '1 roll (8 pcs)',
  }, // estimate
  {
    slug: 'bukka-pounded-yam-egusi',
    name: 'Bukka Plate: Pounded Yam + Egusi',
    category: 'restaurant',
    tags: ['restaurant', 'nigerian', 'bukka'],
    kcal_per_100g: 155,
    protein_per_100g: 5.8,
    carbs_per_100g: 17,
    fat_per_100g: 7,
    fiber_per_100g: 2.2,
    default_serving_g: 450,
    default_serving_label: '1 bukka plate',
  }, // estimate
  {
    slug: 'bukka-ofada-ayamase',
    name: 'Bukka Plate: Ofada + Ayamase + Meat',
    category: 'restaurant',
    tags: ['restaurant', 'nigerian', 'bukka'],
    kcal_per_100g: 185,
    protein_per_100g: 8.0,
    carbs_per_100g: 22.0,
    fat_per_100g: 7.5,
    fiber_per_100g: 2.0,
    default_serving_g: 450,
    default_serving_label: '1 bukka plate',
  }, // estimate
  {
    slug: 'kfc-chicken-original',
    name: 'KFC-style Fried Chicken (original)',
    category: 'restaurant',
    tags: ['restaurant', 'fried', 'poultry'],
    kcal_per_100g: 270,
    protein_per_100g: 22.0,
    carbs_per_100g: 8.0,
    fat_per_100g: 17.0,
    fiber_per_100g: 0.5,
    default_serving_g: 150,
    default_serving_label: '1 piece',
  }, // USDA
  {
    slug: 'burrito-chicken',
    name: 'Chicken Burrito (restaurant)',
    category: 'restaurant',
    tags: ['restaurant', 'mexican', 'wrap'],
    kcal_per_100g: 200,
    protein_per_100g: 10.0,
    carbs_per_100g: 23.0,
    fat_per_100g: 7.5,
    fiber_per_100g: 3.0,
    default_serving_g: 350,
    default_serving_label: '1 burrito',
  }, // estimate
  {
    slug: 'ice-cream-vanilla',
    name: 'Vanilla Ice Cream',
    category: 'restaurant',
    tags: ['restaurant', 'sweet', 'dairy'],
    kcal_per_100g: 207,
    protein_per_100g: 3.5,
    carbs_per_100g: 24.0,
    fat_per_100g: 11.0,
    fiber_per_100g: 0.7,
    default_serving_g: 66,
    default_serving_label: '1 scoop',
  }, // USDA
]
